"""empty message

Revision ID: 672685665819
Revises: e2c4b498b0f0
Create Date: 2024-05-31 13:38:07.676341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672685665819'
down_revision = 'e2c4b498b0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('starship_class', sa.String(), nullable=True),
    sa.Column('hyperdrive_rating', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('crew', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('cost_in_credits', sa.String(), nullable=True),
    sa.Column('cargo_capacity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rotation_period', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('gravity')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('climate')
        batch_op.drop_column('terrain')

    op.drop_table('starships')
    # ### end Alembic commands ###
